project_name: "SCP_GAN_CIFAR10_"

dataset:
  name: "CIFAR10"
  classes: ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

data:
  root: "./data"
  download: True
  num_workers: 4

data_transform:
  tin_mean: [0.5, 0.5, 0.5]
  tin_std : [0.5, 0.5, 0.5]
  aug_images : 10
logger:
  log_dir: "results/logs"
  tensorboard_dir: "results/runs"
  log_file: "training.log"
  level: "INFO"

model:
  latent_dim : 100
  num_classes : 10
  embedding_dim: 50
  generator:
    initial_channels: 256
    channel_sequence: [128, 64]
  discriminator:
    channel_sequence: [64,128,256]
    leak_slope: 0.2

trainer:
  batch_size: 128
  epochs : 100
  lr_g: 0.0002
  lr_d: 0.002
  beta1: 0.5
  beta2: 0999
  device: "mps"

use_pin: False # Turn this to true only when CUDA is Available.
seed: 42
