project_name: "SCP_GAN_CIFAR10_"

logger:
  log_dir: "results/logs"
  tensorboard_dir: "results/runs"
  log_file: "training.log"
  level: "INFO"

model:
  name: "baseline_model"
  latent_dimension: 100
  embedding_dimension: 50
  batch_size: 128
  num_classes: 10
  img_size: 32
  gen_features: 64
  disc_featurs:

trainer:
  batch_size: 128
  epochs : 100
  lr_g: 0.0002
  lr_d: 0.002
  beta1: 0.5
  beta2: 0999
  device: "mps"
  seed: 42
  
data:
  root: "./data"
  download: True
  num_workers: 4


